// Golden-vector tests: vectors.json is generated by the Python side
// (tamper_signal/canonical.py, spec 1.1). Byte equality here is the
// cross-language contract; any failure is a bug in the Node port.

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { test } from "node:test";

import { canonicalize, decimalToPlainString, parseDecimal, semanticHash } from "../canonical.js";

const { vectors } = JSON.parse(readFileSync(new URL("./vectors.json", import.meta.url), "utf-8"));

// {"__date__": "..."} markers become Date instances (midnight UTC); a
// {"__datetime__": "..."} marker carries a real timestamp.
function decode(records) {
  return records.map((record) => {
    const out = {};
    for (const [key, value] of Object.entries(record)) {
      if (value !== null && typeof value === "object" && "__date__" in value) {
        out[key] = new Date(`${value.__date__}T00:00:00Z`);
      } else if (value !== null && typeof value === "object" && "__datetime__" in value) {
        out[key] = new Date(value.__datetime__);
      } else {
        out[key] = value;
      }
    }
    return out;
  });
}

for (const vector of vectors) {
  test(`vector: ${vector.name}`, () => {
    const records = decode(vector.records);
    assert.equal(canonicalize(records).toString("utf-8"), vector.canonical);
    assert.equal(semanticHash(records), vector.semantic_hash);
  });
}

test("decimal parsing accepts the forms Python's Decimal accepts", () => {
  assert.equal(decimalToPlainString(parseDecimal("1.")), "1");
  assert.equal(decimalToPlainString(parseDecimal(".5")), "0.5");
  assert.equal(decimalToPlainString(parseDecimal("+30")), "30");
  assert.equal(decimalToPlainString(parseDecimal("1e3")), "1000");
  assert.equal(decimalToPlainString(parseDecimal("1E+20")), "100000000000000000000");
  assert.equal(parseDecimal("Infinity"), null);
  assert.equal(parseDecimal("NaN"), null);
  assert.equal(parseDecimal("1_000"), null);
  assert.equal(parseDecimal("0x10"), null);
});

test("half-even quantization at the sixth place", () => {
  assert.equal(decimalToPlainString(parseDecimal("0.0000005")), "0"); // ties to even (0)
  assert.equal(decimalToPlainString(parseDecimal("0.0000015")), "0.000002"); // ties to even (2)
  assert.equal(decimalToPlainString(parseDecimal("-0.0000005")), "0"); // negative zero collapses
});
