// Canonicalization and semantic hashing: the Node port of
// tamper_signal/canonical.py. Byte-identical output is the contract; the
// golden vectors in test/vectors.json are generated by the Python side and
// any divergence is a bug here. No dependencies.
//
// Exact decimal arithmetic uses BigInt: a parsed decimal is {v, exp} meaning
// v * 10^exp with v a signed BigInt mantissa. Quantization to six places uses
// round-half-even, matching Python's Decimal(_QUANT, ROUND_HALF_EVEN).
//
// Known divergences from Python, accepted as out of contract:
// - Python's Decimal parses non-ASCII unicode digits; this port does not.
// - Python's str.strip()/\s and JS trim()/\s disagree on U+FEFF.

import { createHash } from "node:crypto";

// ---------------------------------------------------------------------------
// Evidence hash
// ---------------------------------------------------------------------------
export function evidenceHash(rawBytes) {
  return createHash("sha256").update(rawBytes).digest("hex");
}

// ---------------------------------------------------------------------------
// Exact decimals
// ---------------------------------------------------------------------------
const DECIMAL_RE = /^[+-]?(?:(\d+)(?:\.(\d*))?|\.(\d+))(?:[eE]([+-]?\d+))?$/;

// Parse decimal text -> {v: BigInt, exp: number} or null when not a finite
// plain number. Mirrors what survives Python's _coerce_decimal (Infinity and
// NaN parse there but are filtered as non-finite; here they never parse).
export function parseDecimal(text) {
  const t = text.trim();
  if (t === "") return null;
  const m = DECIMAL_RE.exec(t);
  if (!m) return null;
  const neg = t[0] === "-";
  const intPart = m[1] ?? "";
  const fracPart = m[2] ?? m[3] ?? "";
  const exp = (m[4] ? parseInt(m[4], 10) : 0) - fracPart.length;
  const digits = (intPart + fracPart).replace(/^0+(?=\d)/, "") || "0";
  let v = BigInt(digits);
  if (neg) v = -v;
  return { v, exp };
}

// Value * 10^6 as a BigInt, rounded half-even. The only rounding site.
function quantizedUnits({ v, exp }) {
  const neg = v < 0n;
  let mant = neg ? -v : v;
  const shift = exp + 6;
  let units;
  if (shift >= 0) {
    units = mant * 10n ** BigInt(shift);
  } else {
    const divisor = 10n ** BigInt(-shift);
    const q = mant / divisor;
    const r = mant % divisor;
    const twice = r * 2n;
    if (twice > divisor) units = q + 1n;
    else if (twice < divisor) units = q;
    else units = q % 2n === 0n ? q : q + 1n; // tie: round to even
  }
  return neg ? -units : units;
}

// Plain decimal string of a {v, exp} decimal: quantize to six places, strip
// trailing zeros, collapse all zero forms to "0", never scientific notation.
export function decimalToPlainString(dec) {
  let units = quantizedUnits(dec);
  if (units === 0n) return "0";
  const neg = units < 0n;
  if (neg) units = -units;
  const whole = units / 1000000n;
  const frac = (units % 1000000n).toString().padStart(6, "0").replace(/0+$/, "");
  return (neg ? "-" : "") + whole.toString() + (frac ? "." + frac : "");
}

// Exact sum of decimals (used by totals): align mantissas to the smallest
// exponent. Returns {v, exp}.
export function sumDecimals(decimals) {
  if (!decimals.length) return { v: 0n, exp: 0 };
  const exp = Math.min(...decimals.map((d) => d.exp));
  let v = 0n;
  for (const d of decimals) v += d.v * 10n ** BigInt(d.exp - exp);
  return { v, exp };
}

function coerceDecimal(value) {
  if (typeof value === "boolean") return null;
  if (typeof value === "bigint") return { v: value, exp: 0 };
  if (typeof value === "number") {
    if (!Number.isFinite(value)) return null;
    return parseDecimal(String(value));
  }
  if (typeof value === "string") return parseDecimal(value);
  return null;
}

// ---------------------------------------------------------------------------
// Header normalization
// ---------------------------------------------------------------------------
export function normalizeHeader(header) {
  const text = header === null || header === undefined ? "" : String(header);
  return text.normalize("NFC").trim().toLowerCase().replace(/\s+/g, "_");
}

export function normalizeHeaders(headers) {
  const normalized = headers.map(normalizeHeader);
  const counts = new Map();
  for (const name of normalized) counts.set(name, (counts.get(name) ?? 0) + 1);
  const dupes = [...counts.keys()].filter((n) => counts.get(n) > 1).sort();
  if (dupes.length) {
    throw new Error("Duplicate headers after normalization: " + dupes.join(", "));
  }
  return normalized;
}

// ---------------------------------------------------------------------------
// Cell normalization
// ---------------------------------------------------------------------------
function normalizeString(text) {
  return text.normalize("NFC").trim();
}

function formatUtcDate(value) {
  const pad = (n, w = 2) => String(n).padStart(w, "0");
  const date = `${pad(value.getUTCFullYear(), 4)}-${pad(value.getUTCMonth() + 1)}-${pad(value.getUTCDate())}`;
  const midnight =
    value.getUTCHours() === 0 &&
    value.getUTCMinutes() === 0 &&
    value.getUTCSeconds() === 0 &&
    value.getUTCMilliseconds() === 0;
  if (midnight) return date; // dates round-trip through xlsx as midnight datetimes
  return `${date}T${pad(value.getUTCHours())}:${pad(value.getUTCMinutes())}:${pad(value.getUTCSeconds())}Z`;
}

export function normalizeCell(value) {
  if (value === null || value === undefined) return null;
  if (typeof value === "boolean") return value;
  if (value instanceof Date) return formatUtcDate(value);
  if (typeof value === "number") {
    if (!Number.isFinite(value)) {
      // Match Python's str(float) forms: inf / -inf / nan.
      if (Number.isNaN(value)) return "nan";
      return value > 0 ? "inf" : "-inf";
    }
    return decimalToPlainString(parseDecimal(String(value)));
  }
  if (typeof value === "bigint") {
    return decimalToPlainString({ v: value, exp: 0 });
  }
  if (typeof value === "string") {
    // Numeric-looking text canonicalizes as the number it parses to (spec
    // 1.1), so format round-trips that stringify numbers keep the hash.
    const d = parseDecimal(value);
    if (d !== null) return decimalToPlainString(d);
    return normalizeString(value);
  }
  return normalizeString(String(value));
}

// ---------------------------------------------------------------------------
// Records -> canonical bytes
// ---------------------------------------------------------------------------
// Code-point string comparison: Python compares str by code point, while JS
// default sort compares UTF-16 code units. They differ above U+FFFF.
export function codePointCompare(a, b) {
  if (a === b) return 0;
  const ai = a[Symbol.iterator]();
  const bi = b[Symbol.iterator]();
  for (;;) {
    const an = ai.next();
    const bn = bi.next();
    if (an.done && bn.done) return 0;
    if (an.done) return -1;
    if (bn.done) return 1;
    const ac = an.value.codePointAt(0);
    const bc = bn.value.codePointAt(0);
    if (ac !== bc) return ac < bc ? -1 : 1;
  }
}

function sortToken(cell) {
  if (cell === null) return "0:";
  if (typeof cell === "boolean") return "1:" + (cell ? "true" : "false");
  return "2:" + cell;
}

// The canonical table document: { headers, rows } with normalized headers,
// canonical cell forms, and headers/rows sorted deterministically. Its
// canonical JSON bytes are what semanticHash hashes, so this is exactly the
// document the Data tab (table.json) must contain to read as VERIFIED.
export function canonicalDocument(records) {
  // Union of keys across records, first-seen order, then normalized.
  const rawHeaders = [];
  const seen = new Set();
  for (const record of records) {
    for (const key of Object.keys(record)) {
      const marker = normalizeHeader(key);
      if (!seen.has(marker)) {
        seen.add(marker);
        rawHeaders.push(key);
      }
    }
  }
  const headers = normalizeHeaders(rawHeaders);

  const order = [...headers.keys()].sort((i, j) => codePointCompare(headers[i], headers[j]));
  const sortedHeaders = order.map((i) => headers[i]);

  const rows = records.map((record) => {
    const normalizedRecord = {};
    for (const [k, v] of Object.entries(record)) normalizedRecord[normalizeHeader(k)] = v;
    return order.map((i) => normalizeCell(normalizedRecord[headers[i]] ?? null));
  });

  rows.sort((ra, rb) => {
    for (let i = 0; i < ra.length; i++) {
      const c = codePointCompare(sortToken(ra[i]), sortToken(rb[i]));
      if (c !== 0) return c;
    }
    return 0;
  });

  return { headers: sortedHeaders, rows };
}

export function canonicalize(records) {
  return canonicalJsonBytes(canonicalDocument(records));
}

export function semanticHash(records) {
  return createHash("sha256").update(canonicalize(records)).digest("hex");
}

// ---------------------------------------------------------------------------
// Minimal RFC 8785 JCS serializer (receipt bodies and the data document)
// ---------------------------------------------------------------------------
export function canonicalJsonBytes(value) {
  const out = [];
  jcsWrite(value, out);
  return Buffer.from(out.join(""), "utf-8");
}

function jcsWrite(value, out) {
  if (value === null) {
    out.push("null");
  } else if (value === true || value === false) {
    out.push(value ? "true" : "false");
  } else if (typeof value === "number") {
    // Receipt bodies carry integer leaves only (row counts, byte sizes);
    // data leaves were pre-stringified during cell normalization.
    if (!Number.isSafeInteger(value)) throw new TypeError("JCS: non-integer number leaf");
    out.push(String(value));
  } else if (typeof value === "string") {
    out.push(JSON.stringify(value)); // minimal escaping, matches the Python serializer
  } else if (Array.isArray(value)) {
    out.push("[");
    value.forEach((item, i) => {
      if (i) out.push(",");
      jcsWrite(item, out);
    });
    out.push("]");
  } else if (typeof value === "object") {
    out.push("{");
    const keys = Object.keys(value).sort(codePointCompare);
    keys.forEach((key, i) => {
      if (i) out.push(",");
      out.push(JSON.stringify(key));
      out.push(":");
      jcsWrite(value[key], out);
    });
    out.push("}");
  } else {
    throw new TypeError(`JCS cannot serialize value of type ${typeof value}`);
  }
}

export { coerceDecimal };
